var bestplaces = ["swisserland", "kashmir", "dubai", "caneda", "england"];
console.log(bestplaces);
console.log(bestplaces.sort());
console.log(bestplaces);
console.log(bestplaces.reverse());
console.log(bestplaces);
console.log(bestplaces.reverse());
console.log(bestplaces.reverse());
console.log(bestplaces.sort());
console.log(bestplaces.sort());
console.log(bestplaces.reverse());
